POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpbmgiLCJpZCI6IjVkZjljZTI5OGZlYmIwMDg2ZDFjOWYzOSIsImlhdCI6MTU3NjY1MzQ0NH0.WuNJ5H8Oj26W6Utoq7p8gUoIIylz8vAgaVNntKq_m9w

{
  "content": "Note Created by a User 4",
  "important": true
}